- name : varialbe Preferences
  hosts: localhost
  vars:
    WISHES: " Morning from play variable"
  vars_prompt:
    name: " Moring from prompt variable"
    prompt: Please enter the wishes
    private: false

  vars_files:
  - vars.yaml    

  tasks:
  - name: variable pref
    vars:
      WISHES: " Moring from task variable"
    ansible.builtin.debug:
      msg: "Hello, Good{{WISHES}}"  