# - name: Conditions
#   hosts: web
#   become: yes
#   tasks:
#   - name : Check user exist or not
#     ansible.builtin.command: id expense
#     resgister: USER
#     ignore_errors: true  

  # - name: print user info
  #   ansible.builtin.debug:
  #     msg: "User.info : {{User}}"
  # - name : create User
  #   ansible.builtin.command: add user
  #   when: User.rc !=0 

  # - name: Hello
  #   ansible.builtin.debug:
  #     msg: "HEllo"

- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print user information
    ansible.builtin.debug:
      msg: "User info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0 #condition

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"


