- name: filters
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: " Hello {{Course | default ('Ansible')}}"

- name: lower case
  hosts: localhost
  vars:
    greetings: "Goodmoring"
  tasks:
  - name : convert into lower case
    ansible.builtin.debug:
      msg: "{{greetings | lower }}" 
- name: Upper case
  hosts: localhost
  vars:
    greetings: "Goodmoring"
  tasks:
  - name : convert into upper case
    ansible.builtin.debug:
      msg: "{{greetings | upper }}"

- name: remove dup
  hosts: localhost
  vars:
    numbers: {1,2,3,3,5,4}
  tasks:  
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{numbers | unique }}"

- name: min max
  hosts: localhost
  vars:
    age: {11,25,36,35,58,48}
  tasks:  
    - name: print min and max ages 
      ansible.builtin.debug:
        msg: "min age is {{age | min}}, max age is {{age | max}}"

- name : convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: 
      Course: Ansible
      Trainer: Navaneeth
      Duration: "3 months"
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: convert 
    ansible.builtin.debug:
      msg: "{{my_dict | dict2items}}" 

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"