- name: filters
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: " Hello {{Course | default ('Ansible')}}"

- name: lower case
  hosts: localhost
  vars:
    greetings: "Goodmoring"
  tasks:
  - name : convert into lower case
    ansible.builtin.debug:
      msg: "{{greetings | lower }}" 
- name: Upper case
  hosts: localhost
  vars:
    greetings: "Goodmoring"
  tasks:
  - name : convert into upper case
    ansible.builtin.debug:
      msg: "{{greetings | upper }}" 
