- name: filters
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
      msg: " Hello {{Course | default ('Ansible')}}"

- name: lower case
  hosts: localhost
  vars:
    greetings: "Goodmoring"
  tasks:
  - name : convert into lower case
    ansible.builtin.debug:
      msg: "{{greetings | lower }}" 
- name: Upper case
  hosts: localhost
  vars:
    greetings: "Goodmoring"
  tasks:
  - name : convert into upper case
    ansible.builtin.debug:
      msg: "{{greetings | upper }}"

- name: remove dup
  hosts: localhost
  vars:
    numbers: {1,2,3,3,5,4}
  tasks:  
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{numbers | unique | community.general.version_sort }}"

- name: min max
  hosts: localhost
  vars:
    age: {11,25,36,35,58,48}
  tasks:  
    - name: print min and max ages 
      ansible.builtin.debug:
        msg: "min age is {{age | min}}, max age is {{age | max}}"