- name: install and run nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: nginx
      ansible.builtin.service:
        - name: start nginx
          state: started
          enabled: yes  
        
