- name: Variables
  hosts: localhost
  vars:
    Course: Terraform
    Trainer: Navaneeth
    Duration: 120hrs
  tasks:
    - name: print info
      ansible.builtin.debug:
      msg: "I am Learning {{Course}} from {{Trainer}}, Duration is {{Duration}}"  