- name: Variable
  hosts: localhost
  vars:
    Course: Devops
    Trainer: Navaneeth
    Location: Virtually
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "I am learning {{Course}} {{Location}} from {{Trainer}}"
        
    - name : Print over ride info
      vars:
        Course: Terraform
      ansible.builtin.debug:
        msg: "I am learning {{Course}} {{Location}} from {{Trainer}}"     
