- name: variables
  hosts: localhost
  vars:
    Course: Devops
    Trainer: Navaneeth
    Duration: 120 hrs
  
  tasks:
  - name: print Over ride information
    vars:
      Course: Terraform
    ansible.builtin.debug:
      msg: "I am learning {{Course}} from {{Trainer}} Duration is {{Duration}}" 
  
  - name: Print info
    ansible.builtin.debug:
      msg: "I am learning {{Course}} from {{Trainer}} Duration is {{Duration}}"       