# - name: Variables from files
#   hosts: localhost
#   vars_files:
#     - vars.yaml
#   tasks:
#   - name: Print info
#     ansible.builtin.debug:
#       msg: " I am learning {{Course}} from {{Trainer}} Duration is {{Duration}}"

- name : VAriables from file
  hosts: localhost
  var_files:
    - var.yaml
  tasks:
  - name : Print information
    ansible.builtin.debug:
      msg: "I am learning {{Course}} from {{Trainer}} Duration is {{Duration}}"  