- name: Variables from files
  hosts: localhost
  vars_file:
    - vars.yaml
  task:
  - name: Print info
    ansible.builtin.debug:
      msg: " I am learning {{Course}} from {{Trainer}} duration is {{Duration}}"