- name : variables from prompt
  hosts: locahost
  vars_prompt:
  - name : Username
    prompt: Please enter Username
    private: false
    prompt: Please enter password
    private: true
  tasks:
  - name : Print info
    ansible.builtin.debug:
      msg: "Hi Username is : {{Username}} Password is : {{Password}}"  