# - name : variables from prompt
#   hosts: locahost
#   vars_prompt:
#   - name : Username
#     prompt: Please enter Username
#     private: false
#   - name:  
#     prompt: Please enter password
#     private: true
#   tasks:
#   - name : Print info
#     ansible.builtin.debug:
#       msg: "Hi Username is : {{Username}} Password is : {{Password}}"  

- name : variables from prompt
  hosts: localhost
  vars_prompt: 
  - name: Username
    prompt: please enter uname
    private: false
  - name: Password
    prompt: Please enter Pword
    private: true
  tasks:
  - name : print info
    ansible.builtin.debug:
      msg: "Username is : {{Username}} Password is : {{Password}}"     